"""
Calendar Export module for Agentic Calendar.
Generates .ics files for Apple Calendar / Google Calendar import.
"""

from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional
from uuid import uuid4

from icalendar import Calendar, Event, vText

from models import TaskBlock, ScheduledTask, Session
from storage import get_exports_dir


def create_calendar_event(
    task: TaskBlock,
    scheduled: ScheduledTask,
    session_id: Optional[str] = None,
) -> Event:
    """Create an iCalendar event from a scheduled task."""
    event = Event()

    # Required fields
    event.add('summary', task.title)
    event.add('dtstart', scheduled.start)
    event.add('dtend', scheduled.end)

    # Unique identifier
    event.add('uid', f"{scheduled.task_id}-{uuid4()}@agentic-calendar")

    # Description with task details
    description_parts = [task.description]

    if task.priority == "must":
        description_parts.append("\nPriority: Must do")
    else:
        description_parts.append("\nPriority: Nice to have")

    description_parts.append(f"\nEstimated duration: {task.estimated_hours} hours")

    # Add learning resources
    if task.resources:
        description_parts.append("\n\n📚 LEARNING RESOURCES:")
        for res in task.resources:
            resource_type = res.type.upper() if res.type else "RESOURCE"
            description_parts.append(f"\n• [{resource_type}] {res.title}")
            description_parts.append(f"  {res.url}")
            if res.description:
                description_parts.append(f"  {res.description}")

    if session_id:
        description_parts.append(f"\n\nGenerated by Agentic Calendar (Session: {session_id})")

    event.add('description', '\n'.join(description_parts))

    # Set creation timestamp
    event.add('dtstamp', datetime.now())

    # Add categories
    event.add('categories', ['Agentic Calendar', task.priority.upper()])

    # Add URL if there's a primary resource (first one)
    if task.resources and task.resources[0].url:
        event.add('url', task.resources[0].url)

    return event


def generate_ics(
    session: Session,
    filename: Optional[str] = None,
) -> str:
    """
    Generate an .ics file from a session's schedule.

    Args:
        session: The planning session containing tasks and schedule
        filename: Optional custom filename (without .ics extension)

    Returns:
        Path to the generated .ics file
    """
    # Create calendar
    cal = Calendar()

    # Calendar metadata
    cal.add('prodid', '-//Agentic Calendar//EN')
    cal.add('version', '2.0')
    cal.add('calscale', 'GREGORIAN')
    cal.add('method', 'PUBLISH')

    # Add calendar name if we have goal understanding
    if session.goal_understanding:
        cal.add('x-wr-calname', f"Plan: {session.goal_understanding.summary[:50]}")

    # Create a task lookup
    task_lookup = {task.id: task for task in session.task_blocks}

    # Add events for each scheduled task
    for scheduled in session.schedule:
        task = task_lookup.get(scheduled.task_id)
        if task and task.status != "deleted":
            event = create_calendar_event(task, scheduled, session.session_id)
            cal.add_component(event)

    # Generate filename
    if filename is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"agentic_plan_{timestamp}"

    # Ensure .ics extension
    if not filename.endswith('.ics'):
        filename = f"{filename}.ics"

    # Save to exports directory
    exports_dir = get_exports_dir()
    filepath = exports_dir / filename

    with open(filepath, 'wb') as f:
        f.write(cal.to_ical())

    return str(filepath)


def generate_ics_content(session: Session) -> bytes:
    """
    Generate .ics content as bytes (for download without saving).

    Args:
        session: The planning session containing tasks and schedule

    Returns:
        The .ics file content as bytes
    """
    cal = Calendar()

    cal.add('prodid', '-//Agentic Calendar//EN')
    cal.add('version', '2.0')
    cal.add('calscale', 'GREGORIAN')
    cal.add('method', 'PUBLISH')

    if session.goal_understanding:
        cal.add('x-wr-calname', f"Plan: {session.goal_understanding.summary[:50]}")

    task_lookup = {task.id: task for task in session.task_blocks}

    for scheduled in session.schedule:
        task = task_lookup.get(scheduled.task_id)
        if task and task.status != "deleted":
            event = create_calendar_event(task, scheduled, session.session_id)
            cal.add_component(event)

    return cal.to_ical()


def preview_schedule_text(
    session: Session,
) -> str:
    """
    Generate a text preview of the schedule grouped by day.

    Args:
        session: The planning session

    Returns:
        Formatted text representation of the schedule
    """
    if not session.schedule:
        return "No tasks scheduled yet."

    task_lookup = {task.id: task for task in session.task_blocks}

    # Group by date
    by_date = {}
    for scheduled in session.schedule:
        date_key = scheduled.start.date()
        if date_key not in by_date:
            by_date[date_key] = []
        by_date[date_key].append(scheduled)

    # Sort dates
    sorted_dates = sorted(by_date.keys())

    lines = []
    for date in sorted_dates:
        lines.append(f"\n📅 {date.strftime('%A, %B %d, %Y')}")
        lines.append("-" * 40)

        # Sort by start time
        day_schedule = sorted(by_date[date], key=lambda s: s.start)

        for scheduled in day_schedule:
            task = task_lookup.get(scheduled.task_id)
            if task:
                start_time = scheduled.start.strftime("%H:%M")
                end_time = scheduled.end.strftime("%H:%M")
                priority_icon = "🔴" if task.priority == "must" else "🟡"
                lines.append(f"  {priority_icon} {start_time} - {end_time}: {task.title}")

                # Add resources if available
                if task.resources:
                    for res in task.resources:
                        lines.append(f"      📎 {res.title}: {res.url}")

    return "\n".join(lines)
